### PR TITLE
Hub UI tweaks: section--inner spacing, column sizes, button/anchor alignment, box usage

### PR DESCRIPTION
**Pull request by jwijay**
Related to https://github.com/stencila/style/pull/7.

* **fix(signout, signin, beta_token, header, modal):** aligning button styles with stencila brand guidelines (blue rounded buttons) + using three-quarters-sized columns instead of half-sized columns.
* **fix(account_list, project_list, project_archives, project_overview, base):** using columns in base and project_archives. Using section--inner class for project_overview, project_list, and account_list. Aligning buttons and listed items with branding guidelines in account_list, project_list. Using box instead of card.
* **fix(buttons, anchors):** Aligning hub submit button styles with call-to-action. Removing text decoration from buttons. Making sure anchors are underlined/bolded for appropriate elements (not in box, call-to-action, or dropdown-item).

_Projects List (before, using card):_
Screenshot 2019-03-16 18 58 12

_Signin (before, half-sized columns, smaller CTAs, no anchor underlines):_
Screenshot 2019-03-18 19 08 48

_Modal (before, submit button style):_
Screenshot 2019-03-18 19 07 12

_Projects List (after, using box, underlined anchors, and updated CTA style):_
Screenshot 2019-03-18 11 36 59

_Signin (after, using three-quarters-sized columns, aligned CTA/button styles, underlined anchors)_
Screenshot 2019-03-18 19 12 39

_Modal (after, updated submit button and anchor styles):_
Screenshot 2019-03-18 19 12 01

### CODE REVIEW

**Comment by beneboy** [comment]
Screen Shot 2019-03-20 at 5 29 09 AM

Just highlighted a couple of things here:
- Underlines on the icon links, I don't think they should be there
- I think the clickable Directories should be underlined, but not bold

image

There's inconsistent bolding across these buttons. I think this is because some are links and some are buttons. Anyway they should be consistently non-bold.

**Comment by jwijay** [comment]
> Screen Shot 2019-03-20 at 5 29 09 AM
> 
> Just highlighted a couple of things here:
> 
> * Underlines on the icon links, I don't think they should be there
> * I think the clickable Directories should be underlined, but not bold
> 
> image
> 
> There's inconsistent bolding across these buttons. I think this is because some are links and some are buttons. Anyway they should be consistently non-bold.

Thanks for the catch! I'll go make those consistent.

**Comment by jwijay** [comment]
With https://github.com/stencila/style/pull/8 and this PR, will look like this (underlines only on browse anchors, and unbolded buttons/table anchors):
Screenshot 2019-03-19 13 33 29

**Comment by beneboy** [comment]
All good now using 1.10 of style.

**Pull request merged**
