### PR TITLE
Move settings to sidebar

### LINKED ISSUE #874: Improve layout of Account Settings view
Currently the some of the Account settings are listed at the bottom of the Account View page.
To make them more discoverable we should move them to the sidebar as indented sub-items.

Screenshot 2020-11-30 at 17 19 26

### PR DESCRIPTION
**Pull request by alex-ketch**
Close #874 

I've taken this as far as I could for now @nokome. I've listed below the remaining tasks:

- [x] Pass `account` context to the Password, Linked Emails, and other related views
- [x] Add a new `Publishing` settings route
- [x] Only show the nested Account Settings sub-menu items when on one of those pages

### CODE REVIEW

**Comment by nokome** [comment]
@alex-ketch I have ticked off two of the above boxes but have not added a new `Publishing` route. Currently things look OK in desktop mode:

Peek 2021-01-26 18-46

But are broken in mobile:

image

Could you fix that and any other refinements (grey line to left of sub-list could go?)

**Comment by alex-ketch** [comment]
Thanks for getting this sorted @nokome! I've updated the stylings for the sub-nav.
Screenshot 2021-01-26 at 13 39 44@2x

**Comment by nokome** [comment]
I have done the final task of splitting off a Publishing settings page.

I went ahead and added a `is_an_account_settings_page` custom template tag because, especially on menu you need to hide the settings sub-menu when not on a settings page (e.g. on project listings). So we now have the `is-active` class on the Settings table, which looks good on mobile

image

but not so good on desktop:

image

@alex-ketch If you want to fix that feel free. Otherwise I will go ahead and merge.

**Comment by alex-ketch** [comment]
@nokome Let me take a quick stab at it. Will merge shortly either way.

**Pull request merged**
