### PR TITLE
Add project filtering fields

### LINKED ISSUE #705: API: Allow filtering of projects based on current user
Requirements would be to:
- Retrieve a list of Projects a user is a member of, with an optional query parameter for user membership role
- Retrieve a list of Projects given a Google Docs ID, for which that document is a source file for _and_ the user is a member of

### PR DESCRIPTION
**Pull request by nokome**
Closes #705

Please see new API docs for projects:

image

Also, I have added some docs on how to add a source to a project using the API:

image

### CODE REVIEW

**Comment by alex-ketch** [comment]
Unfortunately I wasn't able to get this working @nokome :(
- The `role` filter is causing me issues, on the API docs page it's marked as an `integer` field so it doesn't accept string values (`editor`, etc), and I get a 500 error when making a manual API call.
- I also want to clarify my understanding about how the `role` filter works. If the `role` filter is used on its own, does the API use the `Authorization` header to look up the user?

**Comment by nokome** [comment]
>  on the API docs page it's marked as an integer field so it doesn't accept string values (editor, etc)

Fixed, thanks.

> and I get a 500 error when making a manual API call.

I can't replicate that error:

```sh
> curl http://daniel:daniel@localhost:8000/api/projects\?role=owner
{"count":2,"next":null,"previous":null,"results":[{"id":17,"account":{"id":11,"name":"daniel","user":9,"creator":9,"created":"2020-09-07T01:56:48.481889Z","displayName":"Daniel Colreavy","location":"Dublin","image":"http://localhost:8000/local/media/accounts/images/daniel_MrIUjeb.png","website":null,"email":"daniel@example.edu","theme":null,"extraHead":null,"extraTop":null,"extraBottom":null,"hosts":null},"creator":9,"created":"2020-09-07T01:56:51.145008Z","name":"first-project","title":"First project","description":"A public project for account daniel.","temporary":false,"public":true,"key":"8pPDbPFJfkLaZVg5JF4KG5WFoN4fJVEE","main":"main.md","theme":"rpng","extraHead":null,"extraTop":null,"extraBottom":null,"liveness":"latest","pinned":null,"role":"OWNER"},{"id":18,"account":{"id":11,"name":"daniel","user":9,"creator":9,"created":"2020-09-07T01:56:48.481889Z","displayName":"Daniel Colreavy","location":"Dublin","image":"http://localhost:8000/local/media/accounts/images/daniel_MrIUjeb.png","website":null,"email":"daniel@example.edu","theme":null,"extraHead":null,"extraTop":null,"extraBottom":null,"hosts":null},"creator":9,"created":"2020-09-07T01:56:51.158469Z","name":"second-project","title":"Second project","description":"A private project for account daniel.","temporary":false,"public":false,"key":"bKH9TzKxPdxVmda9YW2rE248qUPmQYrP","main":"main.md","theme":null,"extraHead":null,"extraTop":null,"extraBottom":null,"liveness":"latest","pinned":null,"role":"OWNER"}]}⏎                                                                                                

> curl http://daniel:daniel@localhost:8000/api/projects\?role=editor
{"count":0,"next":null,"previous":null,"results":[]}⏎
```

Edit: I do get that error when not authenticated ie. `curl http://daniel:daniel@localhost:8000/api/projects\?role=editor`. Will look into it.

> I also want to clarify my understanding about how the role filter works. If the role filter is used on its own, does the API use the Authorization header to look up the user?

Yes, the list of project returned is always the list of projects that _the currently authenticated user_ has access to. So, an unauthenticated list will get only public projects, and authenticated request will get public projects plus those that the user is a member of, adding `?role=member` will only return those that the user is a member of (has a role for, any role), adding `?role=manager` will only return projects where the authenticated user has the manager role.

**Comment by nokome** [comment]
Have fixed that error and added some docs to clarify: https://github.com/stencila/hub/pull/708/commits/7f2de626dffc4729f0e951e23caf0009acb12c04

**Comment by alex-ketch** [comment]
Thanks @nokome, the filters are working great. I think there's just one addition I'd like to see in this API, which is ability to to fetch for multiple roles. Either by setting multiple `role` queries, or another flag which gets projects for a certain role or higher.
Use case for this is to fetch a list of projects a user can make contributions for, in this case any of `author`, `editor`, `manager` or `owner` roles is what would meet the criteria. 
Currently this would require network requests as far as I could tell.
I tried setting the `role` query parameter multiple times, but it only returns results for the last role.

**Comment by nokome** [comment]
Hah, yes I was anticipating that request 🙂.

Which of these options would you prefer?

1. Comma separated list e.g. `role=author,editor`

2. Another parameter e.g. `roleAtLeast=author`

**Comment by alex-ketch** [comment]
@nokome I'm torn :/
- `roleAtLeast`:
  - 👍 allows us to somewhat decouple backend models from the API, accommodating future changes
  - 👎 potentially confusing interaction with `role` parameter. Probably best to error, saying to use one or the other?
- `role=author,editor`:
  - 👍 does what it says on the tin
  - 👎 backend model changes could require client changes, but not the end of the world

I can work with either, so will leave you to decide what you feel is best 🙃

**Comment by nokome** [comment]
Thanks. I'll go with `role=author,editor` but also see about having `role=author+` as a way of specifying 'at least author'

**Pull request merged**
